version: '3.8'
services:
  temporal:
    image: temporalio/auto-setup:1.22.3
    environment:
      - DB=sqlite
      - SQLITE_PATH=/etc/temporal/temporal.db
    ports:
      - '7233:7233'
    volumes:
      - temporal-data:/etc/temporal
  temporal-ui:
    image: temporalio/ui:2.23.2
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - '8080:8080'
    depends_on:
      - temporal
volumes:
  temporal-data:
